"""Safe, provider-neutral language-model adapter contracts."""

from ai_parametric_architect.llm.base import (
    LLMConfigurationError,
    LLMContractError,
    LLMOutput,
    LLMOutputKind,
    LLMProvider,
    LLMProviderAuthenticationError,
    LLMProviderError,
    LLMProviderRateLimitError,
    LLMProviderRefusalError,
    LLMProviderResponseError,
    LLMProviderTimeoutError,
    LLMProviderTruncatedError,
    LLMProviderUnavailableError,
    StructuredPrompt,
)
from ai_parametric_architect.llm.prompts import (
    DESIGN_INTENT_OUTPUT_SCHEMA_NAME,
    PROMPT_VERSION,
    design_intent_output_schema,
    design_intent_prompt,
    floor_plan_suggestion_prompt,
    patch_proposal_prompt,
)
from ai_parametric_architect.llm.provider import (
    MOCK_LLM_PROVIDER_NAME,
    MOCK_LLM_PROVIDER_VERSION,
    LLMFloorPlanPlanner,
    LLMPatchProposalGenerator,
    LLMRequirementParser,
    MockLLMProvider,
)

__all__ = [
    "DESIGN_INTENT_OUTPUT_SCHEMA_NAME",
    "MOCK_LLM_PROVIDER_NAME",
    "MOCK_LLM_PROVIDER_VERSION",
    "PROMPT_VERSION",
    "LLMConfigurationError",
    "LLMContractError",
    "LLMFloorPlanPlanner",
    "LLMOutput",
    "LLMOutputKind",
    "LLMPatchProposalGenerator",
    "LLMProvider",
    "LLMProviderAuthenticationError",
    "LLMProviderError",
    "LLMProviderRateLimitError",
    "LLMProviderRefusalError",
    "LLMProviderResponseError",
    "LLMProviderTimeoutError",
    "LLMProviderTruncatedError",
    "LLMProviderUnavailableError",
    "LLMRequirementParser",
    "MockLLMProvider",
    "StructuredPrompt",
    "design_intent_output_schema",
    "design_intent_prompt",
    "floor_plan_suggestion_prompt",
    "patch_proposal_prompt",
]
